"""
Statistical Analysis Script — Generated by Med-Research-Powers
================================================================
Research Question: {research_question}
Analysis Plan: analysis-plan.md
Date: {date}
Author: {author}
================================================================
Environment:
  Python: {version}
  pandas: {pd_version}
  scipy: {scipy_version}
  statsmodels: {sm_version}
Random Seed: 42
================================================================

Skeleton template. Fill each section per analysis-plan.md.
Loads the CLEAN dataset (data_clean.csv) produced in Step 2.4 —
NEVER run downstream analysis on raw data.csv.
"""

import sys, os
import pandas as pd
import numpy as np
from scipy import stats
np.random.seed(42)

# Print environment for reproducibility
print(f"Python {sys.version}")
for pkg in ['pandas', 'numpy', 'scipy', 'statsmodels']:
    print(f"{pkg} {__import__(pkg).__version__}")

# ─── 0. Data Loading ───
# All downstream analysis uses the cleaned dataset from Step 2.4.
df = pd.read_csv('data_clean.csv')
print(f"\n[Data] N={df.shape[0]}, Variables={df.shape[1]}")
print(f"[Data] Missing values:\n{df.isnull().sum()[df.isnull().sum()>0]}")

# ─── 1. Descriptive Statistics ───
# (按 analysis-plan.md Section 3 执行)

# ─── 2. Assumption Tests ───
# (调用 assumption_tests.py)

# ─── 3. Primary Analysis ───
# (按 analysis-plan.md Section 4 逐条执行)
# 每个分析输出: 统计量、p值、效应量、95% CI、样本量

# ─── 4. Secondary / Subgroup Analysis ───
# (按 analysis-plan.md Section 5 执行)

# ─── 5. Sensitivity Analysis ───
# (按 analysis-plan.md Section 6 执行)

# ─── 6. Export Results ───
# results.to_csv('results_tables.csv', index=False)
